### PR TITLE
Updated top text on frontpage

### LINKED ISSUE #76: Remove/Replace spreadsheet option from main page
Let's get rid of the spreadsheet option!  It was a time-limited solution and now we have the requirement for recipients to create their Milestone in the Dapp.  Anyone who has filled out the form up until this issue is completed will of course still receive credit.

We can replace it with a link to this GitHub Repo for people having issues so we can track manage and fix problems:

image

Change text from existing:
Received points this month? Please add your video below, and/or complete this form!

To new:
Received points in Riot? Please add your video below and embed link in your [RewardDAO Milestone](https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424). You can report any issues to our [Github Repo](https://github.com/Giveth/wall-of-fame), Thank you for contributing to Giveth!

### PR DESCRIPTION
**Pull request by iemwill**
Just started the minimum changes, could be working alrdy, dont know. Feel free to complete :)

Fixes #76

### CODE REVIEW

**Comment by FrederikBolding** [comment]
Hi @iemwill - Could you start by verifying that it runs?

**Comment by iemwill** [comment]
yeah sure, will do that but just started it as initial start for me, cant do right now, when i remove WIP in the title its done :)

**Comment by FrederikBolding** [comment]
@iemwill As I am looking at this project right now, will you be finishing this?

**Review by FrederikBolding — APPROVED** [review]

**Comment by FrederikBolding** [comment]
Fixed this and will be merging.

**Pull request merged**
